### ISSUE TITLE
Opencensus metrics do not show in MetricExplorer

### ISSUE THREAD

**Issue by etokarev** [newrelic/newrelic-opencensus-exporter-go#3]
I have a GRPC service application written in Go that uses OpenCensus to collect application metrics and traces. I added NewRelic exporter to transfer app metrics to NewRelic backend. I can pull app metrics on the Chart builder page using the following NRQL query:
```
FROM Metric SELECT uniques(metricName)
```
However I cannot discover them in Data Explorer (NewRelic INSIGHTS -> Data Explorer -> Metrics ) because  my application does not show up in the application list. Also the application does not show up in the NewRelic APM section.

However everything works if I install and configure NewRelic Go agent. I can see my app in APM, all metrics are discoverable, etc

Is it possible to get the same kind of experience that NewRelic Go agent provides with just using OpenCensus + NewRelic exporter?  Ideally I'd like to keep my application logic use the OpenCensus tracing and metric API so the data can be exported to multiple backends like NewRelic and Stackdriver.

**Comment by newrelic-eheinlein** [comment]
Hi @etokarev - thank you for your question.  I have been discussing this internally, and the short answer is that our intention with the Open Telemetry/Open Census work is for the data to be surfaced in the NROne UI (https://one.newrelic.com) rather than in the legacy APM UI. To see your service in NROne, it should show up in the Entity Explorer under Custom Services.

The legacy UI is built expecting a very specific set of metrics that our APM agents are specifically designed to send, and so if you are sending custom metrics via another source, such as the Open Census exporter, the legacy APM UI will not get all of the information that it needs to display the same experience as you see in APM with the language agents.

We do have a team that is focused on building UI experiences for visualizing and exploring this data, and they would love to ask you a few questions and potentially show you a few ideas they are exploring. Would you be open to setting up a call with the team?

CC: @wesrog @tyahn @jkwatson @lykkin

**Comment by etokarev** [comment]
Hi @newrelic-eheinlein,
Thank you for replying. I'd love to have a call with your team. Not sure f I want to post my email address here - how I can contact you?

**Comment by MrAlias** [comment]
@etokarev please send me an email (tyahn@newrelic.com) to set up the call. Looking forward to talking with you.

**Comment by newrelic-eheinlein** [comment]
@etokarev great!  If you could send me your contact information to eheinlein [at] newrelic [dot] com, I will make sure that it gets to the right people to set up a call!

**Comment by purple4reina** [comment]
Going to close as we’re addressing out-of-band. Please be sure to contact us via email if you have further questions regarding this, and if you have other related issues to this codebase please be sure to open another issue. 💜
